name: C/C++ CI

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run Hex
      run: HR_CRCHex.exe 22532_scm.hex CRCSettingsApp-2048K.XML
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: 22532_scm.hex

